import { UNIVERSITIES } from './api';
import { getAvailableInstitutions } from './all-courses';

export interface CourseInfo {
  code: string;
  name: string;
  institution: string;
  institutionCode: string;
  /** Unique key combining institution and code: `${institution}-${code}` */
  key?: string;
}

// Get available institutions (those with data files)
const AVAILABLE_INSTITUTIONS = new Set(getAvailableInstitutions());

// Popular courses database - can be expanded
export const POPULAR_COURSES: CourseInfo[] = [
  // UiO courses
  { code: 'IN2010', name: 'Algoritmer og datastrukturer', institution: 'UiO', institutionCode: '1110' },
  { code: 'IN1010', name: 'Programmering', institution: 'UiO', institutionCode: '1110' },
  { code: 'IN2000', name: 'Objektorientert programmering', institution: 'UiO', institutionCode: '1110' },
  { code: 'IN2090', name: 'Databaser', institution: 'UiO', institutionCode: '1110' },
  { code: 'IN2020', name: 'Systemutvikling', institution: 'UiO', institutionCode: '1110' },
  { code: 'IN2140', name: 'Operativsystemer', institution: 'UiO', institutionCode: '1110' },
  { code: 'STK1100', name: 'Sannsynlighetsregning og statistikk', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT1100', name: 'Kalkulus', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT1110', name: 'Kalkulus og lineær algebra', institution: 'UiO', institutionCode: '1110' },
  { code: 'ECON1100', name: 'Grunnkurs i samfunnsøkonomi', institution: 'UiO', institutionCode: '1110' },
  { code: 'PSYK1001', name: 'Innføring i psykologi', institution: 'UiO', institutionCode: '1110' },
  { code: 'JUS1100', name: 'Rettslære', institution: 'UiO', institutionCode: '1110' },
  
  // NTNU courses
  { code: 'TDT4100', name: 'Objektorientert programmering', institution: 'NTNU', institutionCode: '1150' },
  { code: 'TDT4110', name: 'Datastrukturer og algoritmer', institution: 'NTNU', institutionCode: '1150' },
  { code: 'TDT4120', name: 'Algoritmer og datastrukturer', institution: 'NTNU', institutionCode: '1150' },
  { code: 'TDT4135', name: 'Kunstig intelligens', institution: 'NTNU', institutionCode: '1150' },
  { code: 'TDT4140', name: 'Programvareutvikling', institution: 'NTNU', institutionCode: '1150' },
  { code: 'TDT4145', name: 'Datamodellering og databasesystemer', institution: 'NTNU', institutionCode: '1150' },
  { code: 'TDT4173', name: 'Informasjonssystemer', institution: 'NTNU', institutionCode: '1150' },
  { code: 'TMA4100', name: 'Matematikk 1', institution: 'NTNU', institutionCode: '1150' },
  { code: 'TMA4115', name: 'Kalkulus 3', institution: 'NTNU', institutionCode: '1150' },
  { code: 'TMA4140', name: 'Diskret matematikk', institution: 'NTNU', institutionCode: '1150' },
  
  // UiB courses
  { code: 'INF100', name: 'Grunnkurs i programmering', institution: 'UiB', institutionCode: '1120' },
  { code: 'INF101', name: 'Objektorientert programmering', institution: 'UiB', institutionCode: '1120' },
  { code: 'INF102', name: 'Algoritmer, datastrukturer og programmering', institution: 'UiB', institutionCode: '1120' },
  { code: 'MAT111', name: 'Kalkulus', institution: 'UiB', institutionCode: '1120' },
  
  // NHH courses - Obligatoriske emner (Required courses)
  { code: 'BED1', name: 'Grunnleggende bedriftsøkonomi', institution: 'NHH', institutionCode: '1240' },
  { code: 'IKE1', name: 'Introduksjonskurs i etikk', institution: 'NHH', institutionCode: '1240' },
  { code: 'KOM1', name: 'Kommunikasjon og kunstig intelligens', institution: 'NHH', institutionCode: '1240' },
  { code: 'MET1', name: 'Matematikk for økonomer', institution: 'NHH', institutionCode: '1240' },
  { code: 'RET1', name: 'Rettslære for økonomer', institution: 'NHH', institutionCode: '1240' },
  { code: 'RET1A', name: 'Rettslære for økonomer', institution: 'NHH', institutionCode: '1240' },
  { code: 'SAM1', name: 'Introduksjon til samfunnsøkonomi', institution: 'NHH', institutionCode: '1240' },
  { code: 'SAM1A', name: 'Etikk, økonomi og bærekraft', institution: 'NHH', institutionCode: '1240' },
  { code: 'MET2', name: 'Statistikk for økonomer', institution: 'NHH', institutionCode: '1240' },
  { code: 'SAM2', name: 'Mikroøkonomi', institution: 'NHH', institutionCode: '1240' },
  { code: 'SOL1', name: 'Psykologi og ledelse', institution: 'NHH', institutionCode: '1240' },
  { code: 'BED2', name: 'Finansregnskap', institution: 'NHH', institutionCode: '1240' },
  { code: 'MET3', name: 'Databehandling for økonomer', institution: 'NHH', institutionCode: '1240' },
  { code: 'SOL2', name: 'Markedsføring', institution: 'NHH', institutionCode: '1240' },
  { code: 'BED3', name: 'Investering og finans', institution: 'NHH', institutionCode: '1240' },
  { code: 'MET4', name: 'Empiriske metoder', institution: 'NHH', institutionCode: '1240' },
  { code: 'SAM3', name: 'Makroøkonomi', institution: 'NHH', institutionCode: '1240' },
  { code: 'BED4', name: 'Bedriftsøkonomiske beslutninger', institution: 'NHH', institutionCode: '1240' },
  { code: 'SAM4', name: 'Internasjonal handel og velferdsteori', institution: 'NHH', institutionCode: '1240' },
  { code: 'SAM4A', name: 'Anvendt økonomi', institution: 'NHH', institutionCode: '1240' },
  { code: 'SOL3', name: 'Organisasjonen', institution: 'NHH', institutionCode: '1240' },
  { code: 'BED5', name: 'Økonomisk styring', institution: 'NHH', institutionCode: '1240' },
  { code: 'SOL4', name: 'Strategisk ledelse', institution: 'NHH', institutionCode: '1240' },
  
  // NHH courses - Valgfag (Elective courses)
  { code: 'KOM10', name: 'Artificial intelligence for business communication', institution: 'NHH', institutionCode: '1240' },
  { code: 'FOR14', name: 'Algorithms and Computer Programming with Python', institution: 'NHH', institutionCode: '1240' },
  { code: 'FOR11', name: 'Business Taxation', institution: 'NHH', institutionCode: '1240' },
  { code: 'FOR15', name: 'Environmental Economics and Markets', institution: 'NHH', institutionCode: '1240' },
  { code: 'FOR16', name: 'Sustainable investments', institution: 'NHH', institutionCode: '1240' },
  { code: 'FOR18', name: 'Maritime Economics', institution: 'NHH', institutionCode: '1240' },
  { code: 'FOR19', name: 'Green Digitalization and App Development', institution: 'NHH', institutionCode: '1240' },
  { code: 'FOR20', name: 'Introduction to Blockchain', institution: 'NHH', institutionCode: '1240' },
  { code: 'FOR21', name: 'Eierstyring og Private Equity', institution: 'NHH', institutionCode: '1240' },
  { code: 'SAM12', name: 'International Economic History since 1750', institution: 'NHH', institutionCode: '1240' },
  { code: 'SAM15', name: 'Firm Strategy and Competition', institution: 'NHH', institutionCode: '1240' },
  { code: 'SAM17', name: 'Economics, Behavior and Psychology', institution: 'NHH', institutionCode: '1240' },
  { code: 'SAM20', name: 'Energy, Environment and Sustainability', institution: 'NHH', institutionCode: '1240' },
  { code: 'SAM13', name: 'Norsk økonomisk historie fra 1800 til vår tid', institution: 'NHH', institutionCode: '1240' },
  { code: 'SAM14', name: 'Historical Development of Modern Business', institution: 'NHH', institutionCode: '1240' },
  { code: 'SAM16', name: 'Economic Growth and Development', institution: 'NHH', institutionCode: '1240' },
  { code: 'SAM23', name: 'Climate Policies and Green Investments Opportunities', institution: 'NHH', institutionCode: '1240' },
  { code: 'SAM24', name: 'Incentives, Politics, and Behavior', institution: 'NHH', institutionCode: '1240' },
  { code: 'SAM25', name: 'Shaping the Future of Work: Technology, Skills, and Power', institution: 'NHH', institutionCode: '1240' },
  { code: 'SAM22', name: 'Experimental Methods in Business and Economics', institution: 'NHH', institutionCode: '1240' },
  { code: 'SAM26', name: 'Past and Future of Globalization', institution: 'NHH', institutionCode: '1240' },
  { code: 'SOL13', name: 'Purchasing Strategy and Supply Chain Management', institution: 'NHH', institutionCode: '1240' },
  { code: 'SOL11', name: 'Managing Projects in the Digital Age', institution: 'NHH', institutionCode: '1240' },
  { code: 'SOL21', name: 'Happiness and the Good Life: How to make better decisions', institution: 'NHH', institutionCode: '1240' },
  { code: 'SOL12', name: 'Management Consulting', institution: 'NHH', institutionCode: '1240' },
  { code: 'BED3E', name: 'Finance', institution: 'NHH', institutionCode: '1240' },
  { code: 'FIN11', name: 'Trading and Market Microstructure', institution: 'NHH', institutionCode: '1240' },
  { code: 'FIN14', name: 'Business Cases', institution: 'NHH', institutionCode: '1240' },
  { code: 'FIN16', name: 'Financial Economics', institution: 'NHH', institutionCode: '1240' },
  { code: 'FIN10', name: 'Introductory Applied Finance', institution: 'NHH', institutionCode: '1240' },
  { code: 'RRR10', name: 'Corporate Governance and Management Control', institution: 'NHH', institutionCode: '1240' },
  { code: 'RRR11', name: 'Moderne regnskapsførsel i egen bedrift', institution: 'NHH', institutionCode: '1240' },
  { code: 'RET11', name: 'Juss for næringsdrivende', institution: 'NHH', institutionCode: '1240' },
  { code: 'RET14', name: 'Skatterett', institution: 'NHH', institutionCode: '1240' },
  { code: 'RRR13', name: 'Business ethics, social responsibility, and sustainability', institution: 'NHH', institutionCode: '1240' },
  { code: 'RRR14', name: 'Introduction to Sustainable Business', institution: 'NHH', institutionCode: '1240' },
  { code: 'MAT11', name: 'Differens- og differensiallikninger', institution: 'NHH', institutionCode: '1240' },
  { code: 'MAT12', name: 'Sannsynlighet og data science', institution: 'NHH', institutionCode: '1240' },
  { code: 'MAT10', name: 'Analyse og lineær algebra', institution: 'NHH', institutionCode: '1240' },
  { code: 'MAT14', name: 'Mathematical Finance', institution: 'NHH', institutionCode: '1240' },
  { code: 'MAT16', name: 'Computational Finance with Python', institution: 'NHH', institutionCode: '1240' },
  { code: 'MAT13', name: 'Optimering', institution: 'NHH', institutionCode: '1240' },
  { code: 'MAT15', name: 'Risiko og forsikring', institution: 'NHH', institutionCode: '1240' },
  { code: 'ENG11', name: 'English for leadership communication (C1)', institution: 'NHH', institutionCode: '1240' },
  { code: 'FSK20', name: 'Working successfully across cultures', institution: 'NHH', institutionCode: '1240' },
  { code: 'ENG10', name: 'Effective business communication in English (C1)', institution: 'NHH', institutionCode: '1240' },
  { code: 'FRA21', name: 'Fransk for næringslivet (A0-A2)', institution: 'NHH', institutionCode: '1240' },
  { code: 'FRA22', name: 'Fransk for næringslivet II (B1)', institution: 'NHH', institutionCode: '1240' },
  { code: 'JAP10', name: 'Japansk (A1)', institution: 'NHH', institutionCode: '1240' },
  { code: 'JAP11', name: 'Japansk (A2)', institution: 'NHH', institutionCode: '1240' },
  { code: 'SPA20', name: 'Den spansktalende verden i dag: økonomi, samfunn og kultur (B2)', institution: 'NHH', institutionCode: '1240' },
  { code: 'SPA10', name: 'Spansk språk (B1)', institution: 'NHH', institutionCode: '1240' },
  { code: 'SPA13', name: 'Economía y sociedad en el mundo hispanohablante (B2+)', institution: 'NHH', institutionCode: '1240' },
  { code: 'TYS11', name: 'Tysk for næringslivet II (B2)', institution: 'NHH', institutionCode: '1240' },
  { code: 'TYS10', name: 'Tysk for næringslivet (B1)', institution: 'NHH', institutionCode: '1240' },
  { code: 'INT111', name: 'Praksissemester med fokus på Afrika', institution: 'NHH', institutionCode: '1240' },
  { code: 'INTERN-A-B', name: 'Internship abroad Bachelor', institution: 'NHH', institutionCode: '1240' },
  
  // NHH courses - Valgemner (Master level elective courses)
  { code: 'BUS476', name: 'Data Analysis for Business and Research', institution: 'NHH', institutionCode: '1240' },
  { code: 'EEU415', name: 'Environmental, Social and Governance (ESG) Reporting', institution: 'NHH', institutionCode: '1240' },
  { code: 'EEU416', name: 'CRISIS! Communicating Reputation Issues Sustainably in Intercultural Settings', institution: 'NHH', institutionCode: '1240' },
  { code: 'EEU417', name: 'Managing the Family Business – Strategy, Governance, and Change', institution: 'NHH', institutionCode: '1240' },
  { code: 'ACC412', name: 'Nonprofit Accounting', institution: 'NHH', institutionCode: '1240' },
  { code: 'ACC413', name: 'Sustainability & ESG Reporting', institution: 'NHH', institutionCode: '1240' },
  { code: 'BAN403', name: 'Simulation of Business Processes', institution: 'NHH', institutionCode: '1240' },
  { code: 'BAN404', name: 'Statistical Learning', institution: 'NHH', institutionCode: '1240' },
  { code: 'BAN425', name: 'Applied Risk Management', institution: 'NHH', institutionCode: '1240' },
  { code: 'BAN426', name: 'Applied Data Science', institution: 'NHH', institutionCode: '1240' },
  { code: 'BAN437', name: 'Stochastic optimization using algebraic modelling languages', institution: 'NHH', institutionCode: '1240' },
  { code: 'BAN440', name: 'Data Driven Business Analysis', institution: 'NHH', institutionCode: '1240' },
  { code: 'BAN444', name: 'Digital Identity Management: Technology and Applications', institution: 'NHH', institutionCode: '1240' },
  { code: 'BUS400E', name: 'Management Control', institution: 'NHH', institutionCode: '1240' },
  { code: 'BUS403', name: 'Supply Chain Management', institution: 'NHH', institutionCode: '1240' },
  { code: 'BUS444E', name: 'Econometrics for Business Research', institution: 'NHH', institutionCode: '1240' },
  { code: 'BUS446', name: 'Sustainable Business Models', institution: 'NHH', institutionCode: '1240' },
  { code: 'BUS456', name: 'Behavioral Business Strategy', institution: 'NHH', institutionCode: '1240' },
  { code: 'BUS473', name: 'Platform-based Business Models', institution: 'NHH', institutionCode: '1240' },
  { code: 'CEMS402', name: 'Global Leadership', institution: 'NHH', institutionCode: '1240' },
  { code: 'ECN402', name: 'Econometrics', institution: 'NHH', institutionCode: '1240' },
  { code: 'ECN421', name: 'Behavioral Economics', institution: 'NHH', institutionCode: '1240' },
  { code: 'ECN425', name: 'Solving Economic and Social Problems with Big Data', institution: 'NHH', institutionCode: '1240' },
  { code: 'ECN430', name: 'Empirical Macroeconomics and Finance', institution: 'NHH', institutionCode: '1240' },
  { code: 'ECN434', name: 'International Trade and Globalisation', institution: 'NHH', institutionCode: '1240' },
  { code: 'ECO420', name: 'Corporate Governance', institution: 'NHH', institutionCode: '1240' },
  { code: 'ECO439', name: 'Resource Economics', institution: 'NHH', institutionCode: '1240' },
  { code: 'EEU411', name: 'Leading in the Digital Age', institution: 'NHH', institutionCode: '1240' },
  { code: 'ENE425', name: 'Sustainable Energy', institution: 'NHH', institutionCode: '1240' },
  { code: 'ENE430', name: 'Commodity Trading and Transport', institution: 'NHH', institutionCode: '1240' },
  { code: 'ENE434', name: 'Energy Industry Analytics', institution: 'NHH', institutionCode: '1240' },
  { code: 'ENE436', name: 'Environmental Policy Analysis', institution: 'NHH', institutionCode: '1240' },
  { code: 'ENE456', name: 'Corporate and Private Environmental Responsibility', institution: 'NHH', institutionCode: '1240' },
  { code: 'ENE467', name: 'Energy and Climate Policy', institution: 'NHH', institutionCode: '1240' },
  { code: 'ENE470', name: 'Climate Change: Strategies and Role Play (Model UNFCCC)', institution: 'NHH', institutionCode: '1240' },
  { code: 'ENE471', name: 'Machine Learning for Energy Markets Data', institution: 'NHH', institutionCode: '1240' },
  { code: 'ENE473', name: 'Real Options Analysis of Electricity Markets', institution: 'NHH', institutionCode: '1240' },
  { code: 'ENE475', name: 'Natural Gas Markets', institution: 'NHH', institutionCode: '1240' },
  { code: 'ENE479', name: 'The Economics of Fisheries and Aquaculture Management I', institution: 'NHH', institutionCode: '1240' },
  { code: 'ENE481', name: 'Climate Risk', institution: 'NHH', institutionCode: '1240' },
  { code: 'ENE482', name: 'International Fisheries and Aquaculture Management', institution: 'NHH', institutionCode: '1240' },
  { code: 'ENEINT', name: 'Internship', institution: 'NHH', institutionCode: '1240' },
  { code: 'ETI452', name: 'Diversity and Inclusive Work-life in Firms and Ethics', institution: 'NHH', institutionCode: '1240' },
  { code: 'FIE400E', name: 'Investments', institution: 'NHH', institutionCode: '1240' },
  { code: 'FIE401', name: 'Financial Econometrics', institution: 'NHH', institutionCode: '1240' },
  { code: 'FIE402', name: 'Corporate Finance', institution: 'NHH', institutionCode: '1240' },
  { code: 'FIE421', name: 'Macroeconomic Analysis and Sustainability', institution: 'NHH', institutionCode: '1240' },
  { code: 'FIE432E', name: 'Personal Finance and Taxation', institution: 'NHH', institutionCode: '1240' },
  { code: 'FIE434', name: 'Behavioural Finance and Wealth Management', institution: 'NHH', institutionCode: '1240' },
  { code: 'FIE435', name: 'Financial Modelling with Excel', institution: 'NHH', institutionCode: '1240' },
  { code: 'FIE436', name: 'Venture Capital, Private Equity and IPO\'s', institution: 'NHH', institutionCode: '1240' },
  { code: 'FIE441', name: 'Taxes and Business Strategy', institution: 'NHH', institutionCode: '1240' },
  { code: 'FIE443', name: 'Mergers and Acquisitions', institution: 'NHH', institutionCode: '1240' },
  { code: 'FIE445', name: 'Infrastructure and Project Finance', institution: 'NHH', institutionCode: '1240' },
  { code: 'FIE462', name: 'Finance Innovations in Insurance', institution: 'NHH', institutionCode: '1240' },
  { code: 'FIE463', name: 'Numerical methods in Macroeconomics and Finance using Python', institution: 'NHH', institutionCode: '1240' },
  { code: 'INS420', name: 'Innovation School', institution: 'NHH', institutionCode: '1240' },
  { code: 'INT411', name: 'Internship in Asset Management', institution: 'NHH', institutionCode: '1240' },
  { code: 'INTERN-A-M', name: 'Internship abroad Master', institution: 'NHH', institutionCode: '1240' },
  { code: 'MBM402B', name: 'Brand Management', institution: 'NHH', institutionCode: '1240' },
  { code: 'MBM428', name: 'Product Development and Design', institution: 'NHH', institutionCode: '1240' },
  { code: 'MBM432', name: 'Sustainable Marketing', institution: 'NHH', institutionCode: '1240' },
  { code: 'MBM433', name: 'Customer Analytics in a Digital World', institution: 'NHH', institutionCode: '1240' },
  { code: 'NBD405', name: 'Entrepreneurship and business model design', institution: 'NHH', institutionCode: '1240' },
  { code: 'STR421', name: 'Competitive Strategy', institution: 'NHH', institutionCode: '1240' },
  { code: 'STR463', name: 'Strategy and Technology', institution: 'NHH', institutionCode: '1240' },
  { code: 'STR464', name: 'Cases in Strategy', institution: 'NHH', institutionCode: '1240' },
  { code: 'ACC410', name: 'Finansregnskap II', institution: 'NHH', institutionCode: '1240' },
  { code: 'ACC411', name: 'Regnskap og budsjettering i offentlige organisasjoner', institution: 'NHH', institutionCode: '1240' },
  { code: 'ACC420N', name: 'Regnskapsanalyse', institution: 'NHH', institutionCode: '1240' },
  { code: 'ACC421A', name: 'Verdsettelse', institution: 'NHH', institutionCode: '1240' },
  { code: 'ACC422', name: 'Verdsettelse i regnskapet', institution: 'NHH', institutionCode: '1240' },
  { code: 'BUS401N', name: 'Strategiske lønnsomhetsanalyser', institution: 'NHH', institutionCode: '1240' },
  { code: 'BUS422N', name: 'Investeringsanalyse', institution: 'NHH', institutionCode: '1240' },
  { code: 'BUS428', name: 'Økonomisk organisasjonsteori', institution: 'NHH', institutionCode: '1240' },
  { code: 'BUS432', name: 'Operasjonell planlegging', institution: 'NHH', institutionCode: '1240' },
  { code: 'BUS438', name: 'Strategisk organisering og konkurranse', institution: 'NHH', institutionCode: '1240' },
  { code: 'BUS442', name: 'Konkurranserett', institution: 'NHH', institutionCode: '1240' },
  { code: 'BUS451', name: 'Virksomhetsstyring og AI', institution: 'NHH', institutionCode: '1240' },
  { code: 'BUS467', name: 'Innkjøpsledelse', institution: 'NHH', institutionCode: '1240' },
  { code: 'ECO427', name: 'Strategisk bedriftsadferd og markedsmakt', institution: 'NHH', institutionCode: '1240' },
  { code: 'ECO441', name: 'Skatt og økonomisk politikk', institution: 'NHH', institutionCode: '1240' },
  { code: 'FIE403', name: 'Konjunkturanalyse og makropolitikk', institution: 'NHH', institutionCode: '1240' },
  { code: 'FIE423', name: 'Rentemarkeder og -instrumenter (N)', institution: 'NHH', institutionCode: '1240' },
  { code: 'FIE426', name: 'Kapitalforvaltning', institution: 'NHH', institutionCode: '1240' },
  { code: 'STR402A', name: 'Metode for masterutredningen', institution: 'NHH', institutionCode: '1240' },
  { code: 'STR447', name: 'Strategisk HR', institution: 'NHH', institutionCode: '1240' },
  { code: 'STR453', name: 'Digitalisering', institution: 'NHH', institutionCode: '1240' },
  { code: 'ACC401N', name: 'Finansregnskap I', institution: 'NHH', institutionCode: '1240' },
  { code: 'ACC402N', name: 'Internkontroll og revisjon', institution: 'NHH', institutionCode: '1240' },
  { code: 'ACC421B', name: 'Verdsettelse', institution: 'NHH', institutionCode: '1240' },
  { code: 'ACC440', name: 'Foretaksrett', institution: 'NHH', institutionCode: '1240' },
  { code: 'ACC441', name: 'Skatte- og avgiftsrett', institution: 'NHH', institutionCode: '1240' },
  { code: 'BUS400N', name: 'Styring av større foretak', institution: 'NHH', institutionCode: '1240' },
  { code: 'BUS444N', name: 'Økonometri for regnskap og økonomisk styring', institution: 'NHH', institutionCode: '1240' },
  { code: 'BUS466', name: 'Næringseiendom: investering og forvaltning', institution: 'NHH', institutionCode: '1240' },
  { code: 'BUS475', name: 'Konkurransestrategi', institution: 'NHH', institutionCode: '1240' },
  { code: 'ELE426', name: 'Norwegian Language III Norsk samfunns- og næringsliv', institution: 'NHH', institutionCode: '1240' },
  { code: 'FIE400N', name: 'Finansmarkeder', institution: 'NHH', institutionCode: '1240' },
  { code: 'FIE420', name: 'Pengemarkeder og bankvesen', institution: 'NHH', institutionCode: '1240' },
  { code: 'FIE431', name: 'Krakk og kriser', institution: 'NHH', institutionCode: '1240' },
  { code: 'FIE432', name: 'Personlig økonomi(N)', institution: 'NHH', institutionCode: '1240' },
  { code: 'STR437', name: 'Team og teamledelse', institution: 'NHH', institutionCode: '1240' },
  { code: 'STR446', name: 'Prosessledelse', institution: 'NHH', institutionCode: '1240' },
  { code: 'STR456', name: 'Ledelse og lederpsykologi', institution: 'NHH', institutionCode: '1240' },
  { code: 'ACC401E', name: 'Financial Accounting I', institution: 'NHH', institutionCode: '1240' },
  { code: 'ACC402E', name: 'Internal Control and Audit', institution: 'NHH', institutionCode: '1240' },
  { code: 'ACC420E', name: 'Strategic Financial Statement Analysis', institution: 'NHH', institutionCode: '1240' },
  { code: 'BAN401', name: 'Applied Programming and Data Analysis for Business', institution: 'NHH', institutionCode: '1240' },
  { code: 'BAN402', name: 'Decision Modelling in Business', institution: 'NHH', institutionCode: '1240' },
  { code: 'BAN405', name: 'Python Programming for Data Science', institution: 'NHH', institutionCode: '1240' },
  { code: 'BAN427', name: 'Insurance Analytics', institution: 'NHH', institutionCode: '1240' },
  { code: 'BAN434', name: 'Social and Economic Networks', institution: 'NHH', institutionCode: '1240' },
  { code: 'BAN435', name: 'Blockchain Technology and Applications', institution: 'NHH', institutionCode: '1240' },
  { code: 'BAN441', name: 'Introduction to the use of spatial data', institution: 'NHH', institutionCode: '1240' },
  { code: 'BAN442', name: 'From data to value: Machine Learning with Python', institution: 'NHH', institutionCode: '1240' },
  { code: 'BAN443', name: 'Transforming Business with AI: The Power of Large Language Models', institution: 'NHH', institutionCode: '1240' },
  { code: 'BUS401E', name: 'Strategic Profitability Analysis', institution: 'NHH', institutionCode: '1240' },
  { code: 'BUS452', name: 'Corruption, compliance and sustainable business', institution: 'NHH', institutionCode: '1240' },
  { code: 'BUS474', name: 'Management of Innovation and Intellectual Property', institution: 'NHH', institutionCode: '1240' },
  { code: 'BUS477', name: 'Business Consulting', institution: 'NHH', institutionCode: '1240' },
  { code: 'CEMS401', name: 'Global Strategy', institution: 'NHH', institutionCode: '1240' },
  { code: 'ECN400', name: 'Macroeconomic Theory and Policy', institution: 'NHH', institutionCode: '1240' },
  { code: 'ECN401', name: 'Microeconomic Theory with Applications', institution: 'NHH', institutionCode: '1240' },
  { code: 'ECN423', name: 'Development Economics', institution: 'NHH', institutionCode: '1240' },
  { code: 'ECO400', name: 'Decisions, Strategy and Information', institution: 'NHH', institutionCode: '1240' },
  { code: 'ECO401', name: 'Optimisation and Microeconomic Theory', institution: 'NHH', institutionCode: '1240' },
  { code: 'ECO421', name: 'Asset Pricing', institution: 'NHH', institutionCode: '1240' },
  { code: 'ECO422', name: 'Advanced Corporate Finance', institution: 'NHH', institutionCode: '1240' },
  { code: 'ECO423', name: 'Advanced Derivatives', institution: 'NHH', institutionCode: '1240' },
  { code: 'ECO433', name: 'Empirical Strategies for Causal Analysis', institution: 'NHH', institutionCode: '1240' },
  { code: 'EEU412', name: 'Virtual collaboration across cultures', institution: 'NHH', institutionCode: '1240' },
  { code: 'ENE421', name: 'Energy and Resource Industries', institution: 'NHH', institutionCode: '1240' },
  { code: 'ENE423', name: 'Economics of the Environment and Climate', institution: 'NHH', institutionCode: '1240' },
  { code: 'ENE424', name: 'Elektrisitetsmarkeder', institution: 'NHH', institutionCode: '1240' },
  { code: 'ENE431', name: 'Shipping Economics and Analytics', institution: 'NHH', institutionCode: '1240' },
  { code: 'ENE452', name: 'Seminar: Sustainability and Ethical Challenges', institution: 'NHH', institutionCode: '1240' },
  { code: 'ENE474', name: 'Energy Finance', institution: 'NHH', institutionCode: '1240' },
  { code: 'ENE476', name: 'Offshore Energy Resources', institution: 'NHH', institutionCode: '1240' },
  { code: 'ENE478', name: 'The Economics of Petroleum and the Energy Transition', institution: 'NHH', institutionCode: '1240' },
  { code: 'ENE483', name: 'Sustainable Supply Chain I - Klimapåvirkning av transport, energi og bygninger i leveringskjeder.', institution: 'NHH', institutionCode: '1240' },
  { code: 'ETI450', name: 'Corporate Social Responsibility', institution: 'NHH', institutionCode: '1240' },
  { code: 'FIE425', name: 'Derivatives and Risk Management', institution: 'NHH', institutionCode: '1240' },
  { code: 'FIE433', name: 'International Finance', institution: 'NHH', institutionCode: '1240' },
  { code: 'FIE437', name: 'Valuation', institution: 'NHH', institutionCode: '1240' },
  { code: 'FIE442', name: 'Growth and Architecture of Financial Systems', institution: 'NHH', institutionCode: '1240' },
  { code: 'FIE447', name: 'Trading, Liquidity, and Pricing in Securities Markets', institution: 'NHH', institutionCode: '1240' },
  { code: 'FIE459', name: 'Sustainable Finance', institution: 'NHH', institutionCode: '1240' },
  { code: 'FIE460', name: 'Ship Finance and Marine Insurance', institution: 'NHH', institutionCode: '1240' },
  { code: 'MBM400A', name: 'Research for Business Decisions', institution: 'NHH', institutionCode: '1240' },
  { code: 'MBM401B', name: 'Consumer Behaviour', institution: 'NHH', institutionCode: '1240' },
  { code: 'MBM435', name: 'International Marketing', institution: 'NHH', institutionCode: '1240' },
  { code: 'MBM437', name: 'Introduction to Data Science for Marketing', institution: 'NHH', institutionCode: '1240' },
  { code: 'STR404', name: 'Strategic Analysis', institution: 'NHH', institutionCode: '1240' },
  { code: 'STR445', name: 'Human Capital, Mobility and Diversity in Firms', institution: 'NHH', institutionCode: '1240' },
  { code: 'STR460', name: 'Managing Change and Innovation', institution: 'NHH', institutionCode: '1240' },
  { code: 'STR465', name: 'International Strategy in a Digital World', institution: 'NHH', institutionCode: '1240' },
  
  // NHH - Additional active courses and hvilende emner (currently not offered but may return)
  { code: 'ACC421E', name: 'Valuation with financial statement analysis', institution: 'NHH', institutionCode: '1240' },
  { code: 'BAN400', name: 'R Programming for Data Science', institution: 'NHH', institutionCode: '1240' },
  { code: 'BAN423', name: 'Benchmarking with DEA, SFA, and R', institution: 'NHH', institutionCode: '1240' },
  { code: 'BAN430', name: 'Forecasting', institution: 'NHH', institutionCode: '1240' },
  { code: 'BAN432', name: 'Applied Textual Data Analysis for Business and Finance', institution: 'NHH', institutionCode: '1240' },
  { code: 'BAN439', name: 'Detecting Fraud through Textual Analysis', institution: 'NHH', institutionCode: '1240' },
  { code: 'BUS429', name: 'Pricing Analytics and Revenue Management', institution: 'NHH', institutionCode: '1240' },
  { code: 'BUS465', name: 'Detecting Corporate Crime', institution: 'NHH', institutionCode: '1240' },
  { code: 'BUS469', name: 'Corporate Liability and Sustainable Markets', institution: 'NHH', institutionCode: '1240' },
  { code: 'BUS470', name: 'Strategic Pricing and Competition', institution: 'NHH', institutionCode: '1240' },
  { code: 'BUS472', name: 'Management Control and Public Value Creation in Digital Era', institution: 'NHH', institutionCode: '1240' },
  { code: 'ECN429', name: 'The Economics Of Aquaculture And Fisheries', institution: 'NHH', institutionCode: '1240' },
  { code: 'ECN435', name: 'Data-Driven Public Policy', institution: 'NHH', institutionCode: '1240' },
  { code: 'ECN436', name: 'Economic Inequality and Growth', institution: 'NHH', institutionCode: '1240' },
  { code: 'ECO425', name: 'International Macroeconomics', institution: 'NHH', institutionCode: '1240' },
  { code: 'EEU413', name: 'Sustainability Challenge Summer School', institution: 'NHH', institutionCode: '1240' },
  { code: 'EEU414', name: 'Future of Work', institution: 'NHH', institutionCode: '1240' },
  { code: 'ELE429', name: 'Norwegian economy, history and politics', institution: 'NHH', institutionCode: '1240' },
  { code: 'ENE435', name: 'Sustainable Supply Chain', institution: 'NHH', institutionCode: '1240' },
  { code: 'ENE472', name: 'Canadian and US Energy Markets: Meshed and Challenged', institution: 'NHH', institutionCode: '1240' },
  { code: 'ENE477', name: 'Deep-sea mineral resources', institution: 'NHH', institutionCode: '1240' },
  { code: 'FIE446', name: 'Financial Engineering', institution: 'NHH', institutionCode: '1240' },
  { code: 'FIE448', name: 'Banking and Fintech', institution: 'NHH', institutionCode: '1240' },
  { code: 'FIE450', name: 'Programming with Applications in Finance', institution: 'NHH', institutionCode: '1240' },
  { code: 'FIE453', name: 'Big Data with Applications to Finance', institution: 'NHH', institutionCode: '1240' },
  { code: 'FIE457', name: 'Entrepreneurial Finance', institution: 'NHH', institutionCode: '1240' },
  { code: 'FIE458', name: 'Deep Learning and LLMs with Applications to Finance', institution: 'NHH', institutionCode: '1240' },
  { code: 'FIE461', name: 'Risk and Insurance', institution: 'NHH', institutionCode: '1240' },
  { code: 'MBM424', name: 'Market Communication Effectiveness', institution: 'NHH', institutionCode: '1240' },
  { code: 'MBM431', name: 'Commercialization of Innovations', institution: 'NHH', institutionCode: '1240' },
  { code: 'MBM436', name: 'Strategic Marketing Analytics for Digital Businesses', institution: 'NHH', institutionCode: '1240' },
  { code: 'NBD406', name: 'Strategic Entrepreneurship', institution: 'NHH', institutionCode: '1240' },
  { code: 'NBD413', name: 'Technology Adoption and Consumer Psychology', institution: 'NHH', institutionCode: '1240' },
  { code: 'STR425', name: 'Forhandlinger', institution: 'NHH', institutionCode: '1240' },
  { code: 'STR435', name: 'Personaløkonomi: Lønnsomhet og insentiver', institution: 'NHH', institutionCode: '1240' },
  { code: 'STR436', name: 'Ledelse og organisasjonsbeslutninger', institution: 'NHH', institutionCode: '1240' },
  { code: 'STR452', name: 'Strategy with Finance', institution: 'NHH', institutionCode: '1240' },
  { code: 'STR461', name: 'Strategic and Political Communication', institution: 'NHH', institutionCode: '1240' },
  { code: 'STR462', name: 'Anvendt digitalisering', institution: 'NHH', institutionCode: '1240' },
  
  // More UiO courses
  { code: 'IN1000', name: 'Introduksjon til datamaskiner og datamaskinarkitektur', institution: 'UiO', institutionCode: '1110' },
  { code: 'IN1050', name: 'Brukerorientert design', institution: 'UiO', institutionCode: '1110' },
  { code: 'IN1150', name: 'Webteknologi', institution: 'UiO', institutionCode: '1110' },
  { code: 'STK2100', name: 'Modellering og simulering', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT2400', name: 'Lineær algebra', institution: 'UiO', institutionCode: '1110' },
  
  // More NTNU courses
  { code: 'TDT4180', name: 'Menneske-maskin interaksjon', institution: 'NTNU', institutionCode: '1150' },
  { code: 'TDT4186', name: 'Operativsystemer', institution: 'NTNU', institutionCode: '1150' },
  { code: 'TDT4200', name: 'Algoritmer og datastrukturer', institution: 'NTNU', institutionCode: '1150' },
  
  // UiO Computer Science and Data Science courses
  { code: 'CS5930AMRA', name: 'Applied Mathematics, Mechanics and Numerical Physics, Master thesis', institution: 'UiO', institutionCode: '1110' },
  { code: 'CS5930MECH', name: 'CS: Mechanics - Master thesis', institution: 'UiO', institutionCode: '1110' },
  { code: 'CS5960AMRA', name: 'CS: Applied Mathematics and Risk Analysis - Masteroppgave', institution: 'UiO', institutionCode: '1110' },
  { code: 'CS5960MECH', name: 'CS: Mechanics - Master thesis', institution: 'UiO', institutionCode: '1110' },
  { code: 'DS5930', name: "Master's thesis in Data Science, 30 studiepoeng", institution: 'UiO', institutionCode: '1110' },
  { code: 'DS5960', name: "Master's thesis in Data Science, 60 ECTS", institution: 'UiO', institutionCode: '1110' },
  
  // UiO Mathematics courses
  { code: 'MAT-IN9240', name: 'Numerical analysis of PDEs', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT-INF3600', name: 'Mathematical Logic', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT-MEK4270', name: 'Numerical methods for partial differential equations', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT-MEK9270', name: 'Numerical methods for partial differential equations', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT2000', name: 'Project Work in Mathematics', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT2200', name: 'Groups, Rings and Fields', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT2400', name: 'Real Analysis', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT2410', name: 'Introduction to Complex Analysis', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT3100', name: 'Linear optimization', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT3110', name: 'Introduction to Numerical Analysis', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT3250', name: 'Discrete Mathematics', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT3360', name: 'Introduction to Partial Differential Equations', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT3400', name: 'Linear Analysis with Applications', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT3420', name: 'Quantum Computing', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT3440', name: 'Dynamical systems', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT3500', name: 'Topology', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT4110', name: 'Introduction to Numerical Analysis', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT4120', name: 'Mathematical Optimization', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT4170', name: 'Spline Methods', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT4200', name: 'Commutative Algebra', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT4210', name: 'Algebraic Geometry I', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT4215', name: 'Algebraic Geometry II', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT4230', name: 'Algebraic Geometry III', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT4240', name: 'Elliptic curves', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT4250', name: 'Number Theory', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT4270', name: 'Representation Theory', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT4301', name: 'Partial Differential Equations', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT4305', name: 'Partial Differential Equations and Sobolev Spaces', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT4400', name: 'Linear Analysis with Applications', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT4410', name: 'Advanced Linear Analysis', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT4430', name: 'Quantum information theory', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT4450', name: 'Advanced Functional Analysis', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT4460', name: 'C*-algebras', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT4500', name: 'Topology', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT4510', name: 'Geometric Structures', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT4520', name: 'Manifolds', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT4530', name: 'Algebraic Topology I', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT4540', name: 'Algebraic Topology II', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT4551', name: 'Symplectic geometry', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT4580', name: 'Algebraic Topology III', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT4590', name: 'Differential Geometry', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT4595', name: 'Geometry and analysis', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT4720', name: 'Stochastic Analysis and Stochastic Differential Equations', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT4735', name: 'Advanced financial modelling', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT4740', name: 'Malliavin Calculus and Applications', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT4750', name: 'Mathematical Finance: Modelling and Risk Management', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT4760', name: 'Advanced Mathematical Methods in Finance', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT4770', name: 'Stochastic Modelling in Energy and Commodity Markets', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT4790', name: 'Stochastic Filtering', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT4800', name: 'Complex Analysis', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT4810', name: 'Introduction to Several Complex Variables', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT4820', name: 'Complex Dynamics', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT4830', name: 'Topics in complex analysis and dynamics', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT4930', name: 'Graduate research', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT5930', name: 'Master thesis in Mathematics', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT5960', name: 'Master thesis in Mathematics', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT9120', name: 'Mathematical Optimization', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT9170', name: 'Spline Methods', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT9210', name: 'Algebraic Geometry I', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT9215', name: 'Algebraic Geometry II', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT9230', name: 'Algebraic Geometry III', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT9240', name: 'Elliptic Curves', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT9270', name: 'Representation Theory', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT9305', name: 'Partial Differential Equations and Sobolev Spaces', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT9390', name: 'Topics in Operator Algebras', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT9460', name: 'C*-algebras', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT9520', name: 'Manifolds', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT9530', name: 'Algebraic Topology I', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT9540', name: 'Algebraic Topology II', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT9551', name: 'Symplectic geometry', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT9560', name: 'Lie groups', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT9570', name: 'Algebraic K-theory', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT9580', name: 'Algebraic Topology III', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT9590', name: 'Differential Geometry', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT9595', name: 'Geometry and analysis', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT9650', name: 'Advanced Topics in Logic', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT9720', name: 'Stochastic Analysis and Stochastic Differential Equations', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT9735', name: 'Advanced financial modelling', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT9740', name: 'Malliavin Calculus and Applications', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT9750', name: 'Mathematical Finance: Modelling and Risk Management', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT9760', name: 'Advanced Mathematical Methods in Finance', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT9770', name: 'Stochastic Modelling in Energy and Commodity Markets', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT9790', name: 'Stochastic Filtering', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT9800', name: 'Complex Analysis', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT9810', name: 'Introduction to Several Complex Variables', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT9820', name: 'Complex Dynamics', institution: 'UiO', institutionCode: '1110' },
  { code: 'MAT9830', name: 'Topics in complex analysis and dynamics', institution: 'UiO', institutionCode: '1110' },
  
  // UiO Mechanics courses
  { code: 'MEK3200', name: 'Project Work in Mechanics', institution: 'UiO', institutionCode: '1110' },
  { code: 'MEK3700', name: 'Current topics in bio-mechanics', institution: 'UiO', institutionCode: '1110' },
  { code: 'MEK3800', name: 'Environmental fluid mechanics', institution: 'UiO', institutionCode: '1110' },
  { code: 'MEK4020', name: 'Viscous liquids and elastic materials', institution: 'UiO', institutionCode: '1110' },
  { code: 'MEK4100', name: 'Mathematical Methods in Mechanics', institution: 'UiO', institutionCode: '1110' },
  { code: 'MEK4250', name: 'Finite Element Methods in Computational Mechanics', institution: 'UiO', institutionCode: '1110' },
  { code: 'MEK4300', name: 'Viscous Flow and Turbulence', institution: 'UiO', institutionCode: '1110' },
  { code: 'MEK4320', name: 'Hydrodynamic Wave Theory', institution: 'UiO', institutionCode: '1110' },
  { code: 'MEK4350', name: 'Stochastic and Nonlinear Ocean Waves', institution: 'UiO', institutionCode: '1110' },
  { code: 'MEK4400', name: 'Theory of Hydrodynamic Stability', institution: 'UiO', institutionCode: '1110' },
  { code: 'MEK4410', name: 'Offshore wind and aerodynamics of wind turbines', institution: 'UiO', institutionCode: '1110' },
  { code: 'MEK4420', name: 'Marine Hydrodynamics', institution: 'UiO', institutionCode: '1110' },
  { code: 'MEK4470', name: 'Computational Fluid Mechanics', institution: 'UiO', institutionCode: '1110' },
  { code: 'MEK4480', name: 'Free surface flows', institution: 'UiO', institutionCode: '1110' },
  { code: 'MEK4490', name: 'Project in Fluid Mechanics', institution: 'UiO', institutionCode: '1110' },
  { code: 'MEK4600', name: 'Experimental Methods in Fluid Mechanics', institution: 'UiO', institutionCode: '1110' },
  { code: 'MEK4700', name: 'Current topics in bio-mechanics', institution: 'UiO', institutionCode: '1110' },
  { code: 'MEK4800', name: 'Environmental fluid mechanics', institution: 'UiO', institutionCode: '1110' },
  { code: 'MEK4930', name: 'Graduate research in Mechanics', institution: 'UiO', institutionCode: '1110' },
  { code: 'MEK5930', name: "Master's thesis in Fluid Mechanics, 30 ECTS", institution: 'UiO', institutionCode: '1110' },
  { code: 'MEK5960', name: "Master's thesis in Fluid Mechanics, 60 ECTS", institution: 'UiO', institutionCode: '1110' },
  { code: 'MEK9250', name: 'Finite Element Methods in Computational Mechanics', institution: 'UiO', institutionCode: '1110' },
  { code: 'MEK9300', name: 'Viscous Flow and Turbulence', institution: 'UiO', institutionCode: '1110' },
  { code: 'MEK9320', name: 'Hydrodynamic Wave Theory', institution: 'UiO', institutionCode: '1110' },
  { code: 'MEK9350', name: 'Stochastic and Nonlinear Ocean Waves', institution: 'UiO', institutionCode: '1110' },
  { code: 'MEK9400', name: 'Theory of Hydrodynamic Stability', institution: 'UiO', institutionCode: '1110' },
  { code: 'MEK9410', name: 'Offshore wind and aerodynamics of wind turbines', institution: 'UiO', institutionCode: '1110' },
  { code: 'MEK9420', name: 'Marine Hydrodynamics', institution: 'UiO', institutionCode: '1110' },
  { code: 'MEK9430', name: 'Multiphase Flow', institution: 'UiO', institutionCode: '1110' },
  { code: 'MEK9460', name: 'LES in marine hydrodynamics and offshore wind power', institution: 'UiO', institutionCode: '1110' },
  { code: 'MEK9470', name: 'Computational Fluid Mechanics', institution: 'UiO', institutionCode: '1110' },
  { code: 'MEK9480', name: 'Free Surface Flows', institution: 'UiO', institutionCode: '1110' },
  { code: 'MEK9600', name: 'Experimental Methods in Fluid Mechanics', institution: 'UiO', institutionCode: '1110' },
  
  // UiO Stochastic Modelling, Statistics and Risk Analysis courses
  { code: 'SMR5930', name: 'Stochastic Modelling, Statistics and Risk Analysis', institution: 'UiO', institutionCode: '1110' },
  { code: 'SMR5960', name: "Stochastic Modelling, Statistics and Risk Analysis - Master's Thesis 60 ECTS", institution: 'UiO', institutionCode: '1110' },
  
  // UiO Statistics courses
  { code: 'STK-IN4300', name: 'Statistical Learning Methods in Data Science', institution: 'UiO', institutionCode: '1110' },
  { code: 'STK-IN4355', name: 'Internship in Data Science', institution: 'UiO', institutionCode: '1110' },
  { code: 'STK-IN9300', name: 'Statistical Learning Methods in Data Science', institution: 'UiO', institutionCode: '1110' },
  { code: 'STK-MAT2011', name: 'Project Work in Finance, Insurance, Risk and Data Analysis', institution: 'UiO', institutionCode: '1110' },
  { code: 'STK-MAT3700', name: 'Introduction to Mathematical Finance and Investment Theory', institution: 'UiO', institutionCode: '1110' },
  { code: 'STK-MAT3710', name: 'Probability Theory', institution: 'UiO', institutionCode: '1110' },
  { code: 'STK-MAT4700', name: 'Introduction to Mathematical Finance and Investment Theory', institution: 'UiO', institutionCode: '1110' },
  { code: 'STK-MAT4710', name: 'Probability Theory', institution: 'UiO', institutionCode: '1110' },
  { code: 'STK2100', name: 'Machine Learning and Statistical Methods for Prediction and Classification', institution: 'UiO', institutionCode: '1110' },
  { code: 'STK2130', name: 'Modelling by Stochastic Processes', institution: 'UiO', institutionCode: '1110' },
  { code: 'STK3100', name: 'Introduction to Generalized Linear Models', institution: 'UiO', institutionCode: '1110' },
  { code: 'STK3405', name: 'Introduction to Risk and Reliability Analysis', institution: 'UiO', institutionCode: '1110' },
  { code: 'STK3505', name: 'Introduction to Insurance Mathematics', institution: 'UiO', institutionCode: '1110' },
  { code: 'STK4000', name: 'Special curriculum and seminar', institution: 'UiO', institutionCode: '1110' },
  { code: 'STK4011', name: 'Statistical Inference Theory', institution: 'UiO', institutionCode: '1110' },
  { code: 'STK4021', name: 'Applied Bayesian Analysis', institution: 'UiO', institutionCode: '1110' },
  { code: 'STK4051', name: 'Computational Statistics', institution: 'UiO', institutionCode: '1110' },
  { code: 'STK4060', name: 'Time Series', institution: 'UiO', institutionCode: '1110' },
  { code: 'STK4080', name: 'Survival and Event History Analysis', institution: 'UiO', institutionCode: '1110' },
  { code: 'STK4090', name: 'Statistical large-sample theory', institution: 'UiO', institutionCode: '1110' },
  { code: 'STK4100', name: 'Introduction to Generalized Linear Models', institution: 'UiO', institutionCode: '1110' },
  { code: 'STK4141', name: 'Probabilistic graphical models', institution: 'UiO', institutionCode: '1110' },
  { code: 'STK4150', name: 'Environmental and Spatial Statistics', institution: 'UiO', institutionCode: '1110' },
  { code: 'STK4160', name: 'Statistical Model Selection', institution: 'UiO', institutionCode: '1110' },
  { code: 'STK4180', name: 'Confidence distributions', institution: 'UiO', institutionCode: '1110' },
  { code: 'STK4190', name: 'Bayesian nonparametrics', institution: 'UiO', institutionCode: '1110' },
  { code: 'STK4205', name: 'Short course in selected topics of statistics', institution: 'UiO', institutionCode: '1110' },
  { code: 'STK4215', name: 'Specialized topics in statistics', institution: 'UiO', institutionCode: '1110' },
  { code: 'STK4290', name: 'Selected Themes in Advanced Statistics', institution: 'UiO', institutionCode: '1110' },
  { code: 'STK4400', name: 'Risk and Reliability Analysis', institution: 'UiO', institutionCode: '1110' },
  { code: 'STK4405', name: 'Introduction to Risk and Reliability Analysis', institution: 'UiO', institutionCode: '1110' },
  { code: 'STK4500', name: 'Life Insurance and Finance', institution: 'UiO', institutionCode: '1110' },
  { code: 'STK4505', name: 'Introduction to Insurance Mathematics', institution: 'UiO', institutionCode: '1110' },
  { code: 'STK4530', name: "Interest Rate Modelling via SPDE's", institution: 'UiO', institutionCode: '1110' },
  { code: 'STK4540', name: 'Non-Life Insurance Mathematics', institution: 'UiO', institutionCode: '1110' },
  { code: 'STK4550', name: 'Extreme value statistics and large devia-tions', institution: 'UiO', institutionCode: '1110' },
  { code: 'STK4610', name: 'Statistical methods for social sciences: Survey sampling', institution: 'UiO', institutionCode: '1110' },
  { code: 'STK4900', name: 'Statistical Methods and Applications', institution: 'UiO', institutionCode: '1110' },
  { code: 'STK4930', name: 'Graduate research in Statistics', institution: 'UiO', institutionCode: '1110' },
  { code: 'STK9011', name: 'Statistical Inference Theory', institution: 'UiO', institutionCode: '1110' },
  { code: 'STK9021', name: 'Applied Bayesian Analysis', institution: 'UiO', institutionCode: '1110' },
  { code: 'STK9051', name: 'Computational Statistics', institution: 'UiO', institutionCode: '1110' },
  { code: 'STK9060', name: 'Time Series', institution: 'UiO', institutionCode: '1110' },
  { code: 'STK9080', name: 'Survival and Event History Analysis', institution: 'UiO', institutionCode: '1110' },
  { code: 'STK9090', name: 'Statistical large-sample theory', institution: 'UiO', institutionCode: '1110' },
  { code: 'STK9141', name: 'Probabilistic graphical models', institution: 'UiO', institutionCode: '1110' },
  { code: 'STK9150', name: 'Environmental and Spatial Statistics', institution: 'UiO', institutionCode: '1110' },
  { code: 'STK9160', name: 'Statistical Model Selection', institution: 'UiO', institutionCode: '1110' },
  { code: 'STK9180', name: 'Confidence Distributions', institution: 'UiO', institutionCode: '1110' },
  { code: 'STK9190', name: 'Bayesian nonparametrics', institution: 'UiO', institutionCode: '1110' },
  { code: 'STK9200', name: 'Advanced Statistical Methods', institution: 'UiO', institutionCode: '1110' },
  { code: 'STK9205', name: 'Short Course in Selected Topics of Statistics', institution: 'UiO', institutionCode: '1110' },
  { code: 'STK9215', name: 'Specialized Topics in Statistics', institution: 'UiO', institutionCode: '1110' },
  { code: 'STK9290', name: 'Selected Themes in Advanced Statistics', institution: 'UiO', institutionCode: '1110' },
  { code: 'STK9400', name: 'Risk and Reliability Analysis', institution: 'UiO', institutionCode: '1110' },
  { code: 'STK9500', name: 'Life Insurance and Finance', institution: 'UiO', institutionCode: '1110' },
  { code: 'STK9530', name: "Interest Rate Modelling via SPDE's", institution: 'UiO', institutionCode: '1110' },
  { code: 'STK9550', name: 'Extreme value statistics and large devia-tions', institution: 'UiO', institutionCode: '1110' },
  { code: 'STK9610', name: 'Statistical methods for social sciences: Survey sampling', institution: 'UiO', institutionCode: '1110' },
  { code: 'STK9900', name: 'Statistical Methods and Applications', institution: 'UiO', institutionCode: '1110' },
];

export function searchCourses(query: string, institutionFilter?: string): CourseInfo[] {
  const normalizedQuery = query.trim().toUpperCase();
  if (!normalizedQuery) return [];

  return POPULAR_COURSES.filter((course) => {
    const matchesQuery = 
      course.code.toUpperCase().includes(normalizedQuery) ||
      course.name.toUpperCase().includes(normalizedQuery);
    
    const matchesInstitution = !institutionFilter || course.institution === institutionFilter;
    
    return matchesQuery && matchesInstitution;
  }).slice(0, 10); // Limit to 10 results
}

export function getCourseByCode(code: string, institution?: string): CourseInfo | null {
  const normalizedCode = code.trim().toUpperCase();
  const course = POPULAR_COURSES.find((c) => {
    const matchesCode = c.code.toUpperCase() === normalizedCode;
    const matchesInstitution = !institution || c.institution === institution;
    return matchesCode && matchesInstitution;
  });
  
  return course || null;
}

export function getInstitutionForCourse(courseCode: string): string | null {
  const course = getCourseByCode(courseCode);
  return course ? course.institution : null;
}

export function getCoursesForInstitution(institution: string): CourseInfo[] {
  return POPULAR_COURSES.filter((c) => c.institution === institution);
}

